apps/cms/urls.py
from django.urls import path
from . import views, course_views, staff_views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('banner_list/', views.banner_list, name='banner_list')

]

# 課程相關URL
urlpatterns += [
    path('pub_course/', course_views.PubCourse.as_view(), name='pub_course')
]
# 員工管理
urlpatterns += [
    path('staffs/', staff_views.staffs_view, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff')
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    # path('', views.index, name='index'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('list/', views.news_list, name='news_list'),
    path('public_comment/', views.public_comment, name='public_comment')

]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
    path('cache_test/', views.cache_test, name='cache_test')
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  # path('ueditor/', include('apps.ueditor.urls')),
                  # path('search/', include('haystack.urls')),
                  path('search/', views.search, name='search'),
                  path('news/', include('apps.news.urls')),
                  path('payinfo/', include('apps.payinfo.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include('apps.xfzauth.urls')),
                  path('course/', include('apps.course.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

apps/cms/models.py
from django.db import models

# Create your models here.

apps/cms/forms.py
from apps.forms import FormMixin
from django import forms
from apps.news.models import News, Banner
from apps.course.models import Course


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField()
    name = forms.CharField(max_length=100)


class WriteNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class EditNewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()
    pk = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'author', 'pub_time']


class AddBannerForm(forms.ModelForm, FormMixin):
    class Meta:
        model = Banner
        fields = ('priority', 'link_to', 'image_url')


class EditBannerForm(forms.ModelForm, FormMixin):
    pk = forms.IntegerField()

    class Meta:
        model = Banner
        fields = ('priority', 'link_to', 'image_url')


class PubCourseForm(forms.ModelForm, FormMixin):
    category_id = forms.IntegerField()
    teacher_id = forms.IntegerField()

    class Meta:
        model = Course
        exclude = ("category", 'teacher')

apps/cms/views.py
from django.shortcuts import render
from django.views.generic import View
from apps.news.models import NewsCategory, News, Banner
from utils import restful
from .forms import EditNewsCategoryForm, WriteNewsForm, AddBannerForm, EditBannerForm, EditNewsForm
import os
from django.conf import settings
from apps.news.serializers import BannerSerializer
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse

from django.views.decorators.http import require_POST, require_GET
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


# Create your views here.
@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


@method_decorator(permission_required(perm="news.change_news", login_url='/'), name='dispatch')
class NewsListView(View):
    def get(self, request):
        page = int(request.GET.get('p', 1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        category_id = int(request.GET.get('category', 0) or 0)

        newses = News.objects.select_related('category', 'author').all()

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')  # 函数根据指定的格式把一个时间字符串解析为时间元组。
            else:
                start_date = datetime(year=2019, month=6, day=30)
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.today()
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))
            if title:
                newses = newses.filter(title__icontains=title)  # 不區分大小寫
            if category_id:
                newses = newses.filter(category=category_id)

        paginator = Paginator(newses, 1)  # 可迭代對象,每頁要顯示的條目數量
        page_obj = paginator.page(page)  # 每頁顯示的具體對象
        context_data = self.get_pagination_data(paginator, page_obj)
        context = {
            'categories': NewsCategory.objects.all(),
            'newses': page_obj.object_list,  # 每頁要顯示內容的列表
            'page_obj': page_obj,
            'paginator': paginator,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&' + parse.urlencode({
                # 除頁數外的其他URL參數
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or ''
            })
        }
        context.update(context_data)  # 追加內容到字典中
        return render(request, 'cms/news_list.html', context=context)

    def get_pagination_data(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }


@method_decorator(permission_required(perm="news.add_news", login_url='/'), name='dispatch')
class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category,
                                author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@method_decorator(permission_required(perm="news.change_news", login_url='/'), name='dispatch')
class EditNewsView(View):
    def get(self, request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(pk=news_id)
        context = {
            'news': news,
            'categories': NewsCategory.objects.all()
        }
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = EditNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            pk = form.cleaned_data.get("pk")
            News.objects.filter(pk=pk).update(title=title, desc=desc, thumbnail=thumbnail, content=content,
                                              category=category)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_POST
@permission_required(perm="news.delete_news", login_url='/')
def delete_news(request):
    news_id = request.POST.get('news_id')
    News.objects.filter(pk=news_id).delete()
    return restful.ok()


@require_GET
@permission_required(perm="news.add_newscategory", login_url='/')
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
@permission_required(perm="news.add_newscategory", login_url='/')
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message="該分類已經存在")


@require_POST
@permission_required(perm="news.change_newscategory", login_url='/')
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='該分類不存在')
    else:
        return restful.params_error(message=form.get_error())


@require_POST
@permission_required(perm="news.delete_newscategory", login_url='/')
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message="該分類不存在")


@require_POST
@staff_member_required(login_url='index')
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


@permission_required(perm="news.add_banner", login_url='/')
def banners(request):
    return render(request, 'cms/banners.html')


@permission_required(perm="news.add_newscategory", login_url='/')
def banner_list(request):
    banners = Banner.objects.all()
    serialize = BannerSerializer(banners, many=True)
    return restful.result(data=serialize.data)


@permission_required(perm="news.add_newscategory", login_url='/')
def add_banner(request):
    form = AddBannerForm(request.POST)
    if form.is_valid():
        priority = form.cleaned_data.get('priority')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        banner = Banner.objects.create(priority=priority, image_url=image_url, link_to=link_to)
        return restful.result(data={'banner_id': banner.pk})
    else:
        return restful.params_error(message=form.get_errors())


@permission_required(perm="news.delete_newscategory", login_url='/')
def delete_banner(request):
    banner_id = request.POST.get('banner_id')
    Banner.objects.filter(pk=banner_id).delete()
    return restful.ok()


@permission_required(perm="news.change_newscategory", login_url='/')
def edit_banner(request):
    form = EditBannerForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        image_url = form.cleaned_data.get('image_url')
        link_to = form.cleaned_data.get('link_to')
        priority = form.cleaned_data.get('priority')
        Banner.objects.filter(pk=pk).update(image_url=image_url, link_to=link_to, priority=priority)
        return restful.ok()
    else:
        return restful.params_error(message=form.get_errors())

front/templates/cms/add_staff.html
{% extends 'cms/base.html' %}
{% block title %}
    添加員工
{% endblock %}
{% block head %}
{% endblock %}

{% block content-header %}
    <h1>添加員工</h1>

{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="box">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="box-body">
                        <div class="form-group">
                            <label for="telephone-input">手機號碼</label>
                            <input type="text" class="form-control" name="telephone">
                        </div>
                        <div class="form-group">
                            {% for group in groups %}
                                <label>
                                    <input type="checkbox" name="groups" value="{{ group.pk }}">
                                    {{ group.name }}
                                </label>

                            {% endfor %}
                        </div>
                        <div class="form-group">
                            {% for  message in messages %}
                                {{ message }}
                            {% endfor %}

                        </div>
                    </div>
                    <div class="box-footer">
                        <button class="btn btn-primary pull-right">
                            立即添加
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首頁{% endblock %}

{% block content-header %}
    <h1>歡迎來到小飯桌CMS管理系統</h1>
{% endblock %}
{% block content %}

{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">

    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">

    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/square/blue.css' %}">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="#">小飯桌管理系統</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <p class="login-box-msg">請登錄</p>

        <form action="{% url 'xfzauth:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group has-feedback">
                <input type="text" class="form-control" name="telephone" placeholder="手機號碼">
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" class="form-control" placeholder="密碼">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                    <div class="checkbox icheck">
                        <label>
                            <input type="checkbox" name="remember" value="1"> 記住我
                        </label>
                    </div>
                </div>
                <!-- /.col -->
                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">登錄</button>
                </div>
                <!-- /.col -->
            </div>
        </form>

        <!-- /.social-auth-links -->

        <a href="#">I forgot my password</a><br>
        <a href="register.html" class="text-center">Register a new membership</a>

    </div>
    <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src={% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}></script>
<!-- Bootstrap 3.3.7 -->
<script src={% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}></script>
<!-- iCheck -->
<script src={% static 'adminlte/plugins/iCheck/icheck.min.js' %}></script>

<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}
{% block title %}
    新聞分類
{% endblock %}

{% block head %}

    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    新聞分類
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分類</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>分類名稱</th>
                            <th>新聞數量</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">編輯</button>
                                    <button class="btn btn-danger btn-xs delete-btn">刪除</button>
                                </td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/news_list.html
{% extends 'cms/base.html' %}
{% load news_filters %}
{% block title %}
    新聞列表

{% endblock %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/news_list.min.js' %}"></script>
    <style>
        .left-group {
            margin-right: 20px;
        }
    </style>

{% endblock %}

{% block content-header %}
    <h1>新聞列表管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <form action="" class="form-inline">
                        <div class="form-group left-group">
                            <label for="">時間: </label>
                            {% if start %}
                                <input type="text" class="form-control" name="start" value="{{ start }}"
                                       placeholder="起始時間"
                                       id="start-picker" readonly>
                            {% else %}
                                <input type="text" class="form-control" name="start" placeholder="起始時間"
                                       id="start-picker" readonly>
                            {% endif %}

                            <span>-</span>
                            {% if end %}
                                <input type="text" class="form-control" name="end" value="{{ end }}" placeholder="結束時間"
                                       id="end-picker"
                                       readonly>
                            {% else %}
                                <input type="text" class="form-control" name="end" placeholder="結束時間" id="end-picker"
                                       readonly>
                            {% endif %}

                        </div>
                        <div class="form-group left-group">
                            <label for="title-input">標題: </label>
                            {% if title %}
                                <input type="text" class="form-control" name="title" id="title-input"
                                       value="{{ title }}" placeholder="關鍵字">
                            {% else %}
                                <input type="text" class="form-control" name="title" id="title-input"
                                       placeholder="關鍵字">
                            {% endif %}

                        </div>
                        <div class="form-group left-group">
                            <label for="category-input">分類: </label>
                            <select name="category" id="category-input" class="form-control">
                                {% if category_id == 0 %}
                                    <option value="0" selected>所有分類</option>
                                {% else %}
                                    <option value="0">所有分類</option>
                                {% endif %}
                                {% for category in categories %}
                                    {% if category_id == category.pk %}
                                        <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.pk }}">{{ category.name }}</option>
                                    {% endif %}

                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group left-group">
                            <button class="btn btn-primary">查詢</button>
                        </div>
                        <div class="form-group ">
                            <a href="{% url 'cms:news_list' %}">清除查詢</a>
                        </div>

                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>標題</th>
                            <th>分類</th>
                            <th>發佈時間</th>
                            <th>作者</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for news in newses %}
                            <tr>
                                <td><a href="{% url 'news:news_detail' news_id=news.pk %}"
                                       target="_blank">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time|time_format }}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <a href="{% url 'cms:edit_news' %}?news_id={{ news.pk }}" class="btn btn-info btn-xs">編輯</a>
                                    <button class="btn btn-danger btn-xs delete-btn" data-news-id="{{ news.pk }}">刪除</button>

                                </td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
                <div class="box-footer">
                    <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
                    <ul class="pagination pull-right">
                        {#上一页#}
                        {% if page_obj.has_previous %}
                            <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                        {% endif %}

                        {# 是否需要出现三个点 #}
                        {% if left_has_more %}
                            <li><a href="?p=1">1</a></li>
                            <li><a href="javascript:void(0);">...</a></li>
                        {% endif %}

                        {# 左边的页码 #}
                        {% for left_page in left_pages %}
                            <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                        {% endfor %}

                        {# 当前的页面 #}
                        <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                        {# 右边的页码 #}
                        {% for right_page in right_pages %}
                            <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                        {% endfor %}

                        {# 用来控制右边三个点 #}
                        {% if right_has_more %}
                            <li><a href="javascript:void(0);">...</a></li>
                            <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                        {% endif %}

                        {#下一页#}
                        {% if page_obj.has_next %}
                            <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                        {% else %}
                            <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/staffs.html
{% extends 'cms/base.html' %}

{% block head %}
{% endblock %}

{% block content-header %}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <a href="{% url 'cms:add_staff' %}" class="btn btn-primary pull-right">
                        添加員工
                    </a>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>用戶名</th>
                            <th>手機號</th>
                            <th>所屬分組</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for staff in staffs %}
                            <tr>
                                <td>{{ staff.username }}</td>
                                <td>{{ staff.telephone }}</td>
                                <td>
                                    {% if staff.is_superuser %}
                                        超級管理員
                                    {% else %}
                                        {% for group in staff.groups.all %}
                                            {{ group.name }}/

                                        {% endfor %}
                                    {% endif %}
                                </td>
                                <td>
                                    <button class="btn btn-info btn-xs">
                                        編輯
                                    </button>
                                    <button class="btn btn-info btn-xs">
                                        刪除
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
                <div class="box-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}