apps/cms/urls.py
from django.urls import path
from . import views, course_views, staff_views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('news_list/', views.NewsListView.as_view(), name='news_list'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('delete_news/', views.delete_news, name='delete_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('banners/', views.banners, name='banners'),
    path('add_banner/', views.add_banner, name='add_banner'),
    path('delete_banner/', views.delete_banner, name='delete_banner'),
    path('edit_banner/', views.edit_banner, name='edit_banner'),
    path('banner_list/', views.banner_list, name='banner_list')

]

# 課程相關URL
urlpatterns += [
    path('pub_course/', course_views.PubCourse.as_view(), name='pub_course')
]
# 員工管理
urlpatterns += [
    path('staffs/', staff_views.staffs_view, name='staffs'),
    path('add_staff/', staff_views.AddStaffView.as_view(), name='add_staff')
]

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [

    path('', views.course_index, name='course_index'),
    path('<int:course_id>/', views.course_detail, name='course_detail'),
    path('course_order/<int:course_id>/', views.course_order, name='course_order'),
    path('course_order_key/', views.course_order_key, name="course_order_key"),
    path('notify_view/', views.notify_view, name='notify_view')
]

apps/payinfo/urls.py
from django.urls import path
from . import views

app_name = 'payinfo'

urlpatterns = [

    path('', views.index, name='index'),
    path('payinfo_order/', views.payinfo_order, name='payinfo_order'),
    path('notify/', views.notify_view, name='notify_view'),
    path('download/', views.download, name='download')

]

apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = 'xfzauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('sms_captcha/', views.sms_captcha, name='sms_captcha'),
    path('register/', views.register, name='register'),
    path('cache_test/', views.cache_test, name='cache_test')
]

xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('', views.index, name='index'),
                  # path('ueditor/', include('apps.ueditor.urls')),
                  # path('search/', include('haystack.urls')),
                  path('search/', views.search, name='search'),
                  path('news/', include('apps.news.urls')),
                  path('payinfo/', include('apps.payinfo.urls')),
                  path('cms/', include('apps.cms.urls')),
                  path('account/', include('apps.xfzauth.urls')),
                  path('course/', include('apps.course.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1251408_gbjuowqrtpd.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/xfzajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>

    {% block head %}{% endblock %}
</head>
<body>
<header class="header">
    <div class="container">
        <div class="logo-box">
            <a href="/"></a>
        </div>
        <ul class="nav">
            <li ><a href="/">創業資訊</a></li>
            <li><a href="{% url 'course:course_index' %}">創業課堂</a></li>
            <li><a href="{% url 'payinfo:index' %}">付費資訊</a></li>
            <li><a href="/search/">搜索</a></li>
        </ul>
        <div class="auth-box">
            <i class="icon-person iconfont"></i>
            {% if user.is_authenticated %}
                <a href="#" class="authenticated-box">
                    {{ user.username }}
                </a>
                <div class="user-more-box">
                    <i class="triangle"></i>
                    {% if user.is_staff %}
                        <a href="{% url 'cms:index' %}">管理系统</a>
                        {#                        <a href="#">管理系统</a>#}
                    {% endif %}
                    <a href="{% url 'xfzauth:logout' %}">退出登录</a>

                </div>
            {% else %}
                <a href="#" class="signin-btn">登錄</a> /
                <a href="#" class="signup-btn">注冊</a>
            {% endif %}

        </div>
    </div>
</header>
{% block main %}{% endblock %}
<footer class="footer">
    <div class="top-group">
        <div class="top-inner-group">
            <div class="logo-box"></div>
            <div class="detail-group">
                <div class="line1">
                    <ul class="links">
                        <li><a href="#">關於小飯桌</a></li>
                        <li><a href="#">創業課堂</a></li>
                        <li><a href="#">尋求報道</a></li>
                        <li><a href="#">創業禮包</a></li>
                    </ul>
                    <div class="about-us">
                        <span class="title">關於我們: </span>
                        <ul class="social-group">
                            <li class="weixin">
                                <div class="wx-qrcode"></div>
                                <span class="text">xfz008</span></li>
                            <li class="weibo"><span class="text"><a href="#">小飯桌創業課堂</a></span></li>
                        </ul>
                    </div>
                </div>
                <div class="line2">
                    <p class="address">地址：北京市朝阳区东三环北路38号院1号楼17层2001内1、16室</p>
                    <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                </div>
            </div>
        </div>
    </div>
    <div class="bottom-group">
        ©2017 北京子木投资顾问有限公司 京ICP备15051289号-1
    </div>
</footer>
<div class="mask-wrapper"><!--頁面遮罩層 -->
    <div class="auth-wrapper"><!--注冊登錄頁面最外面的大盒子 -->
        <div class="close-wrapper">
        <span class="close-btn icon-close iconfont">

        </span>
        </div>
        <div class="auth-inner-wrapper">
            <div class="scroll-wrapper"><!-- 表格滑動層-->
                <div class="signin-group auth-group">
                    <div class="top-group">
                        <span class="title">請登錄</span>
                        <a href="javascript:void(0);" class="switch">立即注冊 > </a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" name="telephone" class="form-control" placeholder="請輸入手機號碼">
                        </div>
                        <div class="input-group">
                            <input type="password" name="password" class="form-control" placeholder="請輸入密碼">
                        </div>
                        <div class="input-group">
                            <label class="remember-label"><input type="checkbox" name="remember" value="1">記住我</label>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即登錄">
                        </div>
                    </div>
                </div>
                <div class="signup-group auth-group">
                    <div class="top-group">
                        <span class="title">請注冊</span>
                        <a href="javascript:void(0);" class="switch"> < 立即登錄</a>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <input type="text" name="telephone" class="form-control" placeholder="手機號碼">
                        </div>
                        <div class="input-group">
                            <input type="text" name="username" class="form-control" placeholder="用戶名">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" name="img_captcha" class="form-control" placeholder="驗證碼">
                            </div>
                            <div class="input-group-addon">
                                <img src="{% url 'xfzauth:img_captcha' %}" alt="" class="img-captcha">
                            </div>


                        </div>
                        <div class="input-group">
                            <input type="password" name="password1" class="form-control" placeholder="密碼">
                        </div>
                        <div class="input-group">
                            <input type="password" name="password2" class="form-control" placeholder="確認密碼">
                        </div>
                        <div class="input-group">
                            <div class="short-input-group">
                                <input type="text" name="sms_captcha" class="form-control" placeholder="短信驗證碼">
                            </div>
                            <div class="input-group-addon">
                                <span class="sms-captcha-btn">發送驗證碼</span>
                            </div>
                        </div>
                        <div class="input-group">
                            <input type="submit" class="submit-btn" value="立即注冊">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>